# This is a simple "Guess The Number Game" made in Python 3.0
# This was made for fun and in no way shape or form meant to be a professional code
# I am still a beginner in programming
# Made on 22/9/2018
# Code by funerng
import random

print("This is a game about guessing the number generated by this program\n"
      "You will be prompted to input a number between 1-1000 you think is the correct number\n"
      "You will be told whether or not if the number is higher or lower, so don't worry and have fun!\n"
      "btw there is hard mode which makes it so that you only have 10 guesses before you lose")

# Hardmode is disabled by default
hardmode = False

# Prompts user whether or not to enable Hardmode
def difficulty():
    if input("Enable hardmode? Y/N") == "Y":
        hardmode = True
        print("Hardmode has been enabled")
    else:
        print("Hardmode is disabled")

# Function that starts the game
def startGame():
        if hardmode is True:
            hardMode()
        else:
            easyMode()


# The hard mode game logic
def hardMode():
    answer = random.randint(1, 1000)
    userAnswer = int(input("What  number am i thinking of? :"))
    attempts = 1
    while userAnswer != answer and hardmode == True and attempts != 10:
        difference = userAnswer - answer
        attempts += 1
        if userAnswer > answer and 0 < difference <= 10:
            userAnswer = int(input("The number is lower, you are very close! Try again! "))
        elif userAnswer == 1337:
           print( answer)
           userAnswer = int(input("What  number am i thinking of? :"))
        elif userAnswer < answer and -10 <= difference < 0:
            userAnswer = int(input("The number is higher, you are very close! Try again! "))
        elif userAnswer < answer:
            userAnswer = int(input("The number is higher! Try again!"))
        elif userAnswer > answer:
            userAnswer = int(input("The number is lower! Try again!"))
    if attempts == 10:
        print("You failed")
    if userAnswer == answer:
        print("You are right!")



# The easy mode game logic
def easyMode():
    answer = random.randint(1, 1000)
    userAnswer = int(input("What  number am i thinking of? :"))
    while userAnswer != answer and hardmode == False:
        difference = userAnswer - answer
        if userAnswer > answer and 0 < difference <= 10:
            userAnswer = int(input("The number is lower, you are very close! Try again! "))
        elif userAnswer == 1337:
            print(answer)
            userAnswer = int(input("What  number am i thinking of? :"))
        elif userAnswer < answer and -10 <= difference < 0:
            userAnswer = int(input("The number is higher, you are very close! Try again! "))
        elif userAnswer < answer:
            userAnswer = int(input("The number is higher! Try again!"))
        elif userAnswer > answer:
            userAnswer = int(input("The number is lower! Try again!"))
    if userAnswer == answer:
        print("You are right!")


# starts the game
difficulty()
startGame()

#Loop for restarting game

while input("Do you want to continue? Y/N") == "Y":
    difficulty()
    startGame()


















       
